import "./nav-bar/style.scss"
import "./slide-img/style.scss"
import "./product-frame/style.scss"
import "./footer/style.scss"
import "./cate-bar/style.scss"

export { NavBar } from "./nav-bar/nav-bar"
export { Slideshow } from "./slide-img/slide-img"
export { ProductFrame } from "./product-frame/product-frame"
export { Footer } from "./footer/footer"
export { CateBar } from "./cate-bar/cate-bar"